---
- name: Ensure Nginx YUM repository is present and enabled
  copy:
    src: etc/yum.repos.d/nginx.repo
    dest: /etc/yum.repos.d/nginx.repo
    owner: root
    group: root
    mode: 0644
  tags: [ 'webserver', 'nginx' ]

- name: Ensure Nginx is installed
  yum:
    name: nginx
    state: installed
  tags: [ 'webserver', 'nginx' ]

- name: Make sure firewalld is installed
  yum:
    name: firewalld
    state: installed
  tags: [ 'firewall' ]

- name: Make sure firewalld is running
  service:
    name: firewalld
    state: started
    enabled: yes
  tags: [ 'firewall' ]

- name: Ensure web and SSH ports are open
  firewalld:
    service: "{{ item }}"
    state: enabled
    permanent: true
    immediate: yes
  with_items:
    - "http"
    - "https"
    - "ssh"
  tags: [ 'webserver', 'nginx', 'firewall', 'ssh' ]

- name: Ensure Nginx is started
  service:
    name: nginx
    state: started
  tags: [ 'webserver', 'nginx' ]

- name: Replace default index.html
  copy:
    src: usr/share/nginx/html/index.html
    dest: /usr/share/nginx/html/index.html
  tags: [ 'webserver', 'nginx' ]